### ISSUE TITLE
Allow superscript (i.e. x to the power 2) or subscript in questions and answers.

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#39]
<img width="84" alt="screen shot 2016-08-09 at 3 30 51 pm" src="https://cloud.githubusercontent.com/assets/12655835/17512611/528e1da2-5e46-11e6-93de-e324353267ec.png">

<img width="98" alt="screen shot 2016-08-09 at 3 35 07 pm" src="https://cloud.githubusercontent.com/assets/12655835/17512731/e6c0addc-5e46-11e6-85a0-6a6f231552c4.png">

**Comment by ritzforce** [comment]
Supporting them directly would require a Text Editor like FCK
Currently its supported by adding html tags
for eg

x<sup>2</sup> + 2x +1
x<sub>1</sub> + Y<sub>2</sub> = Z<sub>3</sub>

**Comment by ritzforce** [comment]
<pre> x<sub>1</sub> + Y<sub>2</sub> = Z<sub>3</sub> </pre>

**Comment by ritzforce** [comment]
x&lt;sub&gt;1&lt;/sub&gt; + Y&lt;sub&gt;2&lt;/sub&gt; = Z&lt;sub&gt;3&lt;/sub&gt;

**Comment by dipakprogrammer** [comment]
x<sub>1</sub> + Y<sup>2</sup> = Z<sub>3</sub> is working fine. So that is ok
