### ISSUE TITLE
Exam detail showing wrong value for "Pass Percentage" field and not showing Created Date field value

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#53]
I added Pass Percentage  = 50 but exam detail page showing Pass Percentage = 100
(Edit page is showing correct values as added)

**Comment by ritzforce** [comment]
Created Date is known issue. The Mysql version is old in the trial box, and doesn't support default date value.

**Comment by ritzforce** [comment]
Pass Percentage issue fixed.
