### ISSUE TITLE
Exam Details page (Users Tab) showing internal server error

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#54]
<img width="912" alt="screen shot 2017-09-08 at 8 59 08 pm" src="https://user-images.githubusercontent.com/12655835/30219078-94234b6a-94d8-11e7-905f-e098a7636689.png">

We have one general user (not admin) in database but it is not showing any user in the list. Tried Add User button to add user to this exam but here also not showing any user in the list.

**Comment by ritzforce** [comment]
Fixed. Table Name was incorrect
