### ISSUE TITLE
Internal Server error while sharing exam

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#57]
<img width="1187" alt="screen shot 2017-09-11 at 1 11 01 pm" src="https://user-images.githubusercontent.com/12655835/30263497-c59501fe-96f2-11e7-9fcb-48379ae7bbb5.png">

**Comment by ritzforce** [comment]
There might be a problem with this institute, as the some of the database tables were not in properCase. Should not occur for a new institute
