### ISSUE TITLE
Unshare button not working 

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#58]
<img width="1174" alt="screen shot 2017-09-11 at 1 16 31 pm" src="https://user-images.githubusercontent.com/12655835/30263674-862eb39c-96f3-11e7-9fc5-e86a0b31a970.png">

**Comment by ritzforce** [comment]
Unshare button on active institute acutally does nothing. It just removes the entry for the admins for shared exams.

Since exam is already copied, and the receiving institute might have added / changeds the questions, hence no action is taken.
