### ISSUE TITLE
We have two exams shared with institute but showing only one of them if I login as institute admin

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#59]
<img width="1191" alt="screen shot 2017-09-11 at 1 21 15 pm" src="https://user-images.githubusercontent.com/12655835/30263862-3517d19a-96f4-11e7-8057-af3aa249082b.png">

<img width="865" alt="screen shot 2017-09-11 at 1 23 25 pm" src="https://user-images.githubusercontent.com/12655835/30263918-6d6bd212-96f4-11e7-89e0-99a6c77d263f.png">

**Comment by ritzforce** [comment]
Due to a previous Database error. can ignore, will work for others.
