### ISSUE TITLE
Do not allow institute admin to edit shared exam

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#61]

**Comment by ritzforce** [comment]
This issue is conflict from the original design.
As per the original proposed design, sharing is a just a one time copy. It's editable both by admins and receivers.

https://docs.google.com/document/d/1a7ILSXNxt-qT-W5oQRO6yk7Mcf5Z5NxCwdQh3Y8f-tk/edit

**Comment by dipakprogrammer** [comment]
ok does that mean common exams are being copied into institute specific tables. If so then it is okay.
