### ISSUE TITLE
Institute Logo Size is too small it should allow 100KB at least ....and run time error even trying to upload small size as expected.

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#62]
<img width="644" alt="screen shot 2017-11-09 at 7 57 08 pm" src="https://user-images.githubusercontent.com/12655835/32610298-5a9896bc-c588-11e7-91bd-8dc944f27f2b.png">

**Comment by ritzforce** [comment]
Solved. Logo stored in Google's Storage and link stored in database.
