### ISSUE TITLE
Runtime Error occurs when we click "Add User" button under "Users" tab on Exam detail page 

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#63]
<img width="1189" alt="screen shot 2017-11-09 at 8 05 10 pm" src="https://user-images.githubusercontent.com/12655835/32610606-54c1bdda-c589-11e7-9cbd-74cb7c01d899.png">

**Comment by ritzforce** [comment]
Institute code should be in lowercase. Added check during creation to compulsorily make it lowercase.
