### ISSUE TITLE
App stopped working ... Application error An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#66]
<img width="645" alt="screen shot 2017-11-09 at 11 24 34 pm" src="https://user-images.githubusercontent.com/12655835/32621248-2d335aa0-c5a5-11e7-8b71-100cedd40442.png">

**Comment by ritzforce** [comment]
Should be solved now
