### ISSUE TITLE
Run Time Error if going to reset the password for this particular institute admin user... (not the case for other institute admin users)

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#67]
<img width="1193" alt="screen shot 2017-11-09 at 11 37 53 pm" src="https://user-images.githubusercontent.com/12655835/32621857-35183b8a-c5a7-11e7-865e-0e4726d000aa.png">

**Comment by ritzforce** [comment]
Institute code should be in lowercase. Modified the code for this in Db.
Added check to ensure future institute have lowercase codes
