### ISSUE TITLE
Share one exam with multiple users not working

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#71]
Login as institute admin:
code: ins1
email: admin@admin.com
pwd: ins1

Select one exam and click Users tab, system is throwing error..
 "An internal server error has occurred. Please check the server logs to diagnose the error"
Click Add user button, it showing processing but again throws the same error...
 "An internal server error has occurred. Please check the server logs to diagnose the error"

**Comment by ritzforce** [comment]
Done and deployed.
