### ISSUE TITLE
Please increase font size of institute address in the header.

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#73]
Client Request....  :)
"ADDRESS AND PHONE NUMBER OF CENTER -SHOWING VERY SMALL FONT 
ALSO IN ONE LINE , THIS SHOULD BE IN TWO OR THREE LINES AND SOME MORE BIG FONT"

**Comment by ritzforce** [comment]
Please check the attached screenshot. Is it okay ?
<img width="1433" alt="looksokay" src="https://user-images.githubusercontent.com/888590/33777099-8fea92fa-dc69-11e7-8d74-190be2fb0fea.png">

**Comment by dipakprogrammer** [comment]
<img width="1436" alt="screen shot 2017-12-09 at 1 52 05 pm" src="https://user-images.githubusercontent.com/12655835/33793966-39e340da-dce8-11e7-922a-704a3c6f3320.png">
Even when we are entering address in two rows it show in one single row that destroy the look of the header. It should show the address in same number of lines as it was entered by the super admin while created the institute.

Originally the address was input like this...
<img width="969" alt="screen shot 2017-12-09 at 1 55 37 pm" src="https://user-images.githubusercontent.com/12655835/33793998-bb76eba6-dce8-11e7-9f49-39478a026a35.png">

**Comment by ritzforce** [comment]
Done. increased the font-size a bit. Fixed the issue of showing text in one line.
