### ISSUE TITLE
Please change default logo of the App (for Super Admin) as given in attached image

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#74]
![screen shot 2017-12-06 at 12 18 23 pm](https://user-images.githubusercontent.com/12655835/33681594-0aafa0aa-daeb-11e7-96f5-cd554826bd9e.png)

**Comment by ritzforce** [comment]
Done. Cool Logo
Pata nahi tha, ek designer andar chupa hai :1st_place_medal:

**Comment by dipakprogrammer** [comment]
😊
