### ISSUE TITLE
When we hit the url https://gamma901.herokuapp.com/ it is shows sharma infotech logo. This should be app logo not specific to any institute or should not include Sharma Infotech name in logo.

### ISSUE THREAD

**Issue by dipakprogrammer** [ritzforce/xyz#78]
When we hit the url https://gamma901.herokuapp.com/ it is shows sharma infotech logo. This should be app logo not specific to any institute or should not include Sharma Infotech name in logo.

**Comment by ritzforce** [comment]
Fixed
